version: 2.1
jobs:
  say-hello:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run:
          name: Say hello
          command: |
            echo Hello
            last_tag=$(git describe --tags | grep -o '^[^-]\+')
            echo "${CIRCLE_BRANCH}"
            echo "${last_tag}"
workflows:
  build-workflow:
    jobs:
      - say-hello
